gunrock/gunrock

- CMakeLists.txt
- cmake/GetGitRevisionDescription.cmake
- cmake/GetGitRevisionDescription.cmake.in
- gunrock/util/gitsha1.cpp.in
- gunrock/util/gitsha1.h
- gunrock/util/test_utils.h
- tests/bfs/test_bfs.cu
Putting this back into master; then I'll fix it.
> Jdo gitsha1

- CMakeLists.txt
- gunrock/app/bfs/bfs_enactor.cuh
- gunrock/app/bfs/bfs_functor.cuh
- gunrock/app/bfs/bfs_problem.cuh
- gunrock/app/enactor_base.cuh
- gunrock/app/pr/pr_functor.cuh
- gunrock/app/pr/pr_problem.cuh
- gunrock/graphio/market.cuh
- gunrock/oprtr/advance/kernel.cuh
- gunrock/util/array_utils.cuh
- tests/bfs/test_bfs.cu
- tests/pr/test_pr.cu
have done the ctest and shell script for the outputs. 
Part of the results are: 
****************** test for wrong matrix type ****************************
Please input a wrong file type: 
marke
marke
./bin/HITS
Unspecified graph type.
****************** test for wrong matrix file ****************************
Please input a wrong file name: 
./tests/hello.mtx
./tests/hello.mtx
./bin/HITS
Loading Matrix-market coordinate-formatted graph ...
Input graph file ./tests/hello.mtx does not exist.
./bin/SALSA
Loading Matrix-market coordinate-formatted graph ...
Input graph file ./tests/hello.mtx does not exist.
weitang@slaking:~/bu$ ctest
Test project /home/weitang/bu
Start  1: TEST_BFS
1/13 Test  #1: TEST_BFS .........................   Passed    0.13 sec
Start  2: TEST_BC
2/13 Test  #2: TEST_BC …
> problem #69

- CMakeLists.txt
Issue: #99 @jowens Can you please try this `cmake` on OSX and see if the OpenMP gets detected properly? I will clean it up if it works and submit a new commit.
> Improved support for Finding OpenMP on OSX & Updated version for CUDA & Boost.

- doc/forking_workflow_gunrock.md
Explanation of how we should structure gunrock's development using different forks and pull requests (this pull request being an example).
Sources: https://www.atlassian.com/git/tutorials/comparing-workflows#forking-workflow
> Gunrock's Forking Workflow.

- CMakeLists.txt
- gunrock/util/test_utils.cuh
This is also means for me to test jenkins on `dev` branch.
> Merging CMakeLists.txt (master -> dev) and fixing some warnings in dev branch.

- tests/bc/test_lib_bc.h
- tests/sssp/test_lib_sssp.h
- tests/test.cpp
Unit test compares expected output values of scores array to those that are generated.
> added BC unit test

- CMakeLists.txt
This doesn't solve the volta issue.
> Adding SM70, 71 (voltas) and enabled 35 (tesla).

- CMakeLists.txt
- gunrock/util/cuda_properties.cuh
- scripts/standard/pr-test.sh
Check out the last commit in this PR.
> Updating CUDA Architecture properties.

- README.md
README.md is the only file that will be required to be updated, this is what we were talking about @jowens. Could you please look at this and merge in (or let me know what needs to be changed)? After this, I will push in the gunrock/docs update so it takes in this README for index.html.
> Updating README to match index.html.md.

- README.md
Add code snippet for build to top of README.md
> [docs] adding quickstart code

- docker/ubuntu16.04-cuda9.0/README.md
- docker/ubuntu16.04-cuda9.1/README.md
> [docker] add README.md

- examples/astar/run.sh
- examples/hits/run.sh
- examples/hits/test_hits.cu
- examples/sm/CMakeLists.txt
> Adding missing run scripts and cmake file for SM.

- gunrock/app/Template/Template_problem.cuh
Patching `BaseDataSlice::Init` incorrect call to in `Template_problem.cuh`
> [dev-refactor] Fix incorrect call in Template_problem.cuh

- gunrock/app/mf/mf_app.cu
- gunrock/app/mf/mf_enactor.cuh
- gunrock/app/mf/mf_problem.cuh
- gunrock/app/mf/mf_test.cuh
- tests/mf/CMakeLists.txt
- tests/mf/Makefile
- tests/mf/test_mf.cu
> Updated MF app and tests files (WIP)

- gunrock/app/sssp/sssp_app.cu
patch incorrect calls to SetPointer in sssp_app.cu
> patch incorrect calls to SetPointer in sssp_app.cu

- gunrock/app/rw/rw_app.cu
- gunrock/app/rw/rw_enactor.cuh
- gunrock/app/rw/rw_problem.cuh
- gunrock/app/rw/rw_test.cuh
- tests/rw/Makefile
- tests/rw/test_rw.cu
This coarsely follows the implementation on the dev branch:
- https://github.com/gunrock/gunrock/tree/dev/gunrock/app/rw
This _does not_ follow the advance/filter paradigm, so the `Enactor::Core` function looks substantially different than `sssp`, `vn`, `hello` or `bc`. It just has a call to `ForAll`, which records the the current node in the walk and replaces the elements of the queue with a (uniformly sampled) random neighbor.
`pygunrock` implementation available here:
- https://github.com/bkj/pygunrock/blob/master/apps/rw.py
To see differences between this implementation and the `hello` app, look at this commit:
- https://github.com/bkj/gunrock/commit/5730703efbe1f9a52d3218bd0ebb9e023d3e166a
- Need to ensure that all edges in the random walk are real edges.  How could we test that it's …
> [dev-refactor][HIVE] random walk app

- CMakeLists.txt
- gunrock/graphio/grmat.cuh
- tests/grmat/Makefile
- tests/grmat/test_grmat.cu
There was no explicit option to use grmat functionality to generate the graph for external use. 
This implementation can write the edge list information to a file or return a pointer which can be used. For pointer usage, the user has to modify the function as currently the pointer is getting freed at the end.
I am working in NVIDIA and this implementation would be helpful in different scenarios.
> Generates graph as an edge list using grmat

- gunrock/app/pr_nibble/pr_nibble_enactor.cuh
- gunrock/app/pr_nibble/pr_nibble_problem.cuh
- gunrock/app/pr_nibble/pr_nibble_test.cuh
- gunrock/app/proj/proj_app.cu
- gunrock/app/proj/proj_problem.cuh
- gunrock/app/proj/proj_test.cuh
- gunrock/app/rw/rw_app.cu
- gunrock/app/rw/rw_enactor.cuh
- gunrock/app/rw/rw_test.cuh
- tests/pr/test_pr.cu
This PR includes a few small changes that fix bugs / bad design that I encountered while testing `pr_nibble`, `rw` and `proj`.
I can explain individual changes as needed, but there's nothing particularly interesting here.
> [dev-refactor][HIVE] hotfixes for testing

- gunrock/app/bc/bc_enactor.cuh
- gunrock/app/pr/pr_enactor.cuh
- gunrock/app/wtf/wtf_enactor.cuh
- gunrock/util/global_barrier.cuh
- gunrock/util/info.cuh
- gunrock/util/kernel_runtime_stats.cuh
> Replacing Thread -> Device. (dev)

- gunrock/app/gtf/gtf_app.cu
- gunrock/app/gtf/gtf_enactor.cuh
- gunrock/app/gtf/gtf_problem.cuh
- gunrock/app/gtf/gtf_test.cuh
- gunrock/app/mf/mf_app.cu
- gunrock/app/mf/mf_enactor.cuh
- gunrock/app/mf/mf_helpers.cuh
- gunrock/app/mf/mf_problem.cuh
- gunrock/app/mf/mf_test.cuh
- gunrock/graphio/market.cuh
- tests/gtf/_data/generate_graph.py
- tests/gtf/_data/taxi_tsv_file_preprocessing.py
- tests/gtf/test_gtf.cu
- tests/mf/test_mf.cu
List of known issues:
1. Fork-Fulkerson algorithm or parametric maxflow generate different final results from PR on GTF (starting from 400 vertices). 
2. Residual graphs diverge starting from around 2-3 iterations and on after calling the maxflow between CPU and GPU implementation of push-relabel. 
3. Maxflow hangs on some generated graphs and some residual graphs of the NY taxi dataset. 
Time scale (an example of one iteration):
num edges: 3160 
______GPU SFL algorithm____
mf: 178.892851 ms (includes mf.enactor.reset and mf.problem.reset)
gtf: 0.124931 ms (sequential implementation of min-cut and some for loops)
> [dev-refactor][HIVE][do not merge] graph-trend-filtering/sparse-graph-lasso

- gunrock/app/knn/knn_app.cu
- gunrock/app/knn/knn_enactor.cuh
- gunrock/app/knn/knn_problem.cuh
- gunrock/app/knn/knn_test.cuh
- tests/knn/Makefile
- tests/knn/test_knn.cu
Project @agalup and I are working on for anomaly detection on botnet or other network related datasets. 
**TODOs:**
> [WIP][do-not-merge] shared-nearest-neighbor/k-nearest-neighbor

- gunrock/app/knn/knn_app.cu
- gunrock/app/knn/knn_problem.cuh
- gunrock/app/knn/knn_test.cuh
- tests/knn/test_knn.cu
Project (@neoblizz and @agalup) working on for anomaly detection on botnet or other network related datasets. 
**TODOs:**
> shared-nearest-neighbor/k-nearest-neighbor

- gunrock/app/knn/knn_app.cu
- gunrock/app/knn/knn_problem.cuh
- gunrock/app/knn/knn_test.cuh
- tests/knn/test_knn.cu
Adding core points and clusters counters. 
Adding omp pragmas to speed up cpu reference.
> core-points and clusters counter

- gunrock/app/knn/knn_app.cu
- gunrock/app/knn/knn_enactor.cuh
- gunrock/app/knn/knn_test.cuh
- tests/BaseMakefile.mk
- tests/knn/test_knn.cu
Updating BaseMakefile.mk to exclude GEN_35 because of RepeatFor Operetor - and some KNN clean-up.
> Minor updates: KNN/BaseMakefile

- CMakeLists.txt
- Jenkinsfile
- examples/tc/test_tc.cu
- gunrock/app/tc/tc_enactor.cuh
- gunrock/app/tc/tc_functor.cuh
- gunrock/app/tc/tc_problem.cuh
+ Minor change: Moved `TC` from global_indicator to app.
> Codecov is now optional

- gunrock/app/tc/tc_enactor.cuh
- gunrock/app/tc/tc_problem.cuh
- gunrock/app/tc/tc_test.cuh
> [BugFix] Solved bug raised in Issue #483

- Jenkinsfile
- README.md
Fixing some formatting and links.
>  Updating dev -> master after the merge.

- examples/wtf/CMakeLists.txt
- gunrock/app/wtf/wtf_enactor.cuh
- gunrock/app/wtf/wtf_functor.cuh
- gunrock/oprtr/edge_map_partitioned/kernel.cuh
Fix for issue #503, needs further testing to make sure the primitive works as intended.
> Fixes illegal memory access bug in WTF.

- gunrock/app/tc/tc_problem.cuh
This fixes the issue #519 .
@Laurawly can review this.
> [TC] fixing extract bug

- unittests/pr/test_lib_pr.h
- unittests/test.cpp
Converted the shared lib test from the master branch into a Google test.
> Pagerank correctness test for pagerank scores

- CMakeLists.txt
- README.md
- examples/mst/CMakeLists.txt
- gunrock/util/device_intrinsics.cuh
> Merging CUDA 9+ support from V1.0 to V0.5.

- unittests/test_binarysearch.h
- unittests/test_unittests.cu
This PR has very minor additions that mimic other Gunrock google tests.
> Add binary search google test

- gunrock/graph/csr.cuh
I have a a debug version of the changed csr.cuh file on my local machine that can be run in nsight debugger to confirm that my function works.
> solution to git issue #454

- gunrock/app/sm/sm_app.cu
- gunrock/gunrock.h
> move sm_app header to gunrock.h

- gunrock/app/hello/hello_test.cuh
- gunrock/graphio/rmat.cuh
@aschaffer I ended up adding grmat functionality to rmat with a parameter that you can set. Will that work for you, or do you guys need it in a separate file (I wanted to avoid redundant code).
> Support for GPU RMAT generator.

- gunrock/app/sm/sm_app.cu
- gunrock/app/sm/sm_app.cuh
- gunrock/app/sm/sm_enactor.cuh
- gunrock/app/sm/sm_test.cuh
@aschaffer Could you take a look to see if the added function means what you raised in the issue [here](https://github.com/gunrock/gunrock/pull/606)? @neoblizz Could you check if `typedef` could be used in the way exposed in `nv_sm`. I'll remove the comments once it meets the needs. Thanks!
> Added wrapper function to pass two graphs to sm

- examples/bfs/test_bfs.cu
- examples/sssp/test_sssp.cu
- examples/vn/test_vn.cu
- gunrock/app/bfs/bfs_app.cu
- gunrock/app/sage/sage_test.cuh
- gunrock/app/sssp/sssp_app.cu
- gunrock/app/vn/vn_app.cu
Modifications for **error: no matching function for call**
https://github.com/gunrock/gunrock/issues/633
> modifications to fix #633

- gunrock/app/sm/sm_app.cu
- gunrock/app/sm/sm_app.cuh
- gunrock/app/sm/sm_test.cuh
@neoblizz @porumbes Could you help review?
> Add boost cpu reference for subgraph matching

- gunrock/app/sm/sm_app.cuh
- gunrock/app/sm/sm_enactor.cuh
> Update subgraph matching enactor reset function

- examples/shared_libs/CMakeLists.txt
- examples/shared_libs/shared_lib_hits.c
- examples/shared_libs/shared_lib_pr.c
- gunrock/app/hits/hits_app.cu
- gunrock/app/hits/hits_app.cuh
- gunrock/gunrock.h
Adds a functional C interface to gunrock.h and implements a shared library test for the HITS algorithm.
This pull request is in response to #616
> Implemented a working HITS shared lib test

- examples/shared_libs/shared_lib_sm.c
- gunrock/app/sm/sm_app.cu
- gunrock/app/sm/sm_app.cuh
- gunrock/app/sm/sm_enactor.cuh
- gunrock/app/sm/sm_problem.cuh
- unittests/test_lib_sm.h
Solving issue #656 
@neoblizz @johari
> [Bugfix] Fix subgraph matching google test 

- examples/sm/test_sm.cu
- gunrock/app/sm/sm_app.cuh
- gunrock/app/sm/sm_enactor.cuh
- gunrock/app/sm/sm_problem.cuh
- gunrock/app/sm/sm_test.cuh
This pr fixes the correction issue for query graph other than triangles. It uses combination method to store intermediate results iteration by iteration.
> Fix bugs for subgraph matching

- cmake/AutoDetectCudaArch.cmake
- gunrock/oprtr/intersection/kernel.cuh
- gunrock/util/device_intrinsics.cuh
- unittests/test_lib_sm.h
Update google test for subgraph matching to make count to be the number of matched subgraphs. Changing according to the merge of PR #678
> Update google test for subgraph matching

- gunrock/util/info_rapidjson.cuh
Draft pull request for changes to JSON writer. I've already done some testing locally, so I'd just appreciate another pair of eyes on these changes. 
TODO:
> Initial JSON writer improvements

- gunrock/app/pr/pr_test.cuh
I believe both of those issues are related to this bug, I am not 100% positive about #683 though. Let's see what Jenkins has to say.
> Workaround for the PageRank Validation SegFault (issue #684 and #683)

- examples/dynamic_graph/test_dynamic_graph.cu
- gunrock/app/app_base.cuh
- gunrock/graph/dynamic_graph/dynamic_graph.cuh
- gunrock/graph/dynamic_graph/dynamic_graph_base.cuh
- gunrock/graph/dynamic_graph/dynamic_graph_unweighted.cuh
- gunrock/graph/dynamic_graph/dynamic_graph_weighted.cuh
- gunrock/graph/dynamic_graph/kernels/map/helper.cuh
- gunrock/graph/dynamic_graph/kernels/map/insert.cuh
- gunrock/graph/dynamic_graph/kernels/set/insert.cuh
- gunrock/graph/dynamic_graph/slabhash_graph_base.cuh
- gunrock/graph/dynamic_graph/slabhash_graph_map.cuh
- gunrock/graph/dynamic_graph/slabhash_graph_set.cuh
- gunrock/graphio/market.cuh
- unittests/test_dynamic_graph.h
Only formatting the files. No code changes.
> Formatting dynamic graph files

- gunrock/graph/dynamic_graph/dynamic_graph_unweighted.cuh
- gunrock/graph/dynamic_graph/dynamic_graph_weighted.cuh
- gunrock/graph/dynamic_graph/kernels/map/delete.cuh
- gunrock/graph/dynamic_graph/kernels/set/insert.cuh
- gunrock/graph/dynamic_graph/slabhash_graph_base.cuh
- gunrock/graph/dynamic_graph/slabhash_graph_map.cuh
- gunrock/graph/dynamic_graph/slabhash_graph_set.cuh
- unittests/test_dynamic_graph.h
- Added weighted directed and undirected edge deletion and their testing
- Update SlabHash to latest
> Adding edge deletion for dynamic graph

- gunrock/util/array_utils.cuh
Extend the `Print` function to print either to stdout (default) or a file.
> Add the option to print to a file

- gunrock/app/enactor_helper.cuh
> issue #761 - commented printf within enactor.

- gunrock/oprtr/intersection/kernel.cuh
Changes make sure that the Intersection kernel (which assumes input CSR graph) is only called when the graph is CSR.
> Adding graph switch for intersect 

- gunrock/app/app_base.cuh
- gunrock/graph/csr_parallel_iterator.cuh
- gunrock/graph/dynamic_graph/dynamic_graph_base.cuh
- gunrock/graph/dynamic_graph/dynamic_graph_parallel_iterator.cuh
- gunrock/graph/dynamic_graph/slabhash_graph_base.cuh
- gunrock/graph/dynamic_graph/slabhash_graph_map.cuh
- gunrock/graph/dynamic_graph/slabhash_graph_parallel_iterator.cuh
- gunrock/graph/dynamic_graph/slabhash_graph_set.cuh
- gunrock/graph/graph_iterator.cuh
- unittests/test_graph_iterator.h
- unittests/test_simple_advance.h
- Separated the dynamic graph iterator and slab hash graph iterator
- Fixed bug in tests (added test graphs freeing)
- Added missing const qualifier in iterators
> Dynamic graph iterator organized

- examples/dynamic_graph/CMakeLists.txt
- examples/dynamic_graph/bulk_build.sh
- examples/dynamic_graph/test_dynamic_graph.cu
- examples/dynamic_graph/validation.cuh
- gunrock/graph/dynamic_graph/dynamic_graph_base.cuh
- gunrock/graph/dynamic_graph/slabhash_graph_base.cuh
- gunrock/graph/dynamic_graph/slabhash_graph_map.cuh
- gunrock/graph/dynamic_graph/slabhash_graph_parallel_iterator.cuh
- gunrock/graph/dynamic_graph/slabhash_graph_set.cuh
- Updated the bulk build example for benchmarking
- Separated initializing the hash tables from bulk build/conversion
> Bulk build example

- examples/bc/test_bc.cu
- examples/bfs/test_bfs.cu
- examples/color/test_color.cu
- examples/geo/test_geo.cu
- examples/hits/test_hits.cu
- examples/knn/test_knn.cu
- examples/louvain/test_louvain.cu
- examples/pr/test_pr.cu
- examples/pr_nibble/test_pr_nibble.cu
- examples/proj/test_proj.cu
- examples/rw/test_rw.cu
- examples/sage/test_sage.cu
- examples/sm/test_sm.cu
- examples/ss/test_ss.cu
- examples/sssp/CMakeLists.txt
- examples/sssp/test_sssp.cu
- examples/tc/test_tc.cu
- examples/vn/test_vn.cu
- gunrock/app/bfs/bfs_app.cu
- gunrock/app/pr/pr_app.cu
- gunrock/app/sssp/sssp_app.cu
See #773 
Creating for build and test. I want to take a closer look at #774 before pulling.
> Fix for specifying quick and validation #773

- examples/api_test/Makefile
- examples/api_test/test_colorapi.cu
- examples/api_test/test_ssspapi.cu
- examples/color/test_color.cu
- examples/sssp/test_sssp.cu
- gunrock/app/color/color_app.cuh
- gunrock/app/sssp/sssp_app.cuh
- gunrock/gunrock.hpp
An example of what changes are needed to support the C++-interface.
- Graph Coloring (Issue #817)
- SSSP
> Gunrock CXX interface

- gunrock/oprtr/1D_oprtr/for_all.cuh
- gunrock/util/array_utils.cuh
@porumbes is there a better already existing way you're doing the following?
```cpp
int num_gpus = -1;
cudaGetDeviceCount(&num_gpus);
```
For now, it can just be another hack in `Array1D` to get this working.
> cudaMallocManaged, Hints, Read-Only (replaces graphs)

- examples/mf/test_mf.cu
- gunrock/app/gtf/gtf_app.cu
- gunrock/app/gtf/gtf_enactor.cuh
- gunrock/app/gtf/gtf_problem.cuh
- gunrock/app/mf/mf_enactor.cuh
- gunrock/app/mf/mf_problem.cuh
See this issues for some comments: https://github.com/owensgroup/hiveapps/issues/23
> Multi-GPU gtf and maxflow changes

- gunrock/app/knn/knn_enactor.cuh
In KNN enactor, changed the ValueT size on sizeof(ValueT) after 32bit and 64bit allowed
> Issue gunrock#855

- gunrock/util/reduce_device.cuh
- gunrock/util/select_device.cuh
- gunrock/util/sort_device.cuh
Reverts gunrock/gunrock#900 - going to double check this first
> Revert "Use external CUB API instead of internal ones"

- gunrock/app/color/color_enactor.cuh
Alessandro (@LeaX-XIV) was kind enough to resolve the infinite loop bug for coloring.
> Restore regeneration of rand array every other iteration

- include/gunrock/formats/csc.hxx
@neoblizz I am directly merging this into develop since it is a bug fix.
> Fix bug: CSC values missing 

- examples/algorithms/CMakeLists.txt
- examples/algorithms/bfs/bfs.cu
- examples/algorithms/dawn/CMakeLists.txt
- examples/algorithms/dawn/dawn_bfs.cu
- include/gunrock/algorithms/dawn.hxx
- include/gunrock/io/parameters.hxx
This pull request aims to propose the DAWN.  GPU version is OK. Thank you for your time and attention!
> Feature: DAWN on unweighted graph
