gunrock/gunrock

gunrock/gunrock.h
Fixes issues with gcc 5.x which use c99 as the default C standard.
=> Fixing linking issues when using C99

CMakeLists.txt, dep/install_boost.sh, dep/install_metis.sh
CMakeLists.txt now gives a warning if metis was not found, and also directs the users to the `dep/` directory where shell scripts for installing metis or boost on non-ubuntu linux users can be found.
=> Addresses issue #76, allows users to install metis or boost.

gunrock/util/sysinfo.h
This resolves #113, by checking for null pointers.
`getlogin()` has also been replaced by `getpwuid(getuid())` as this seems to be the more reliable alternative. 
However I don't expect this will work on Windows (#107)
=> Replace getlogin() and handle null pointers (#113)

CMakeLists.txt
All other tests pass, dobfs and topk run but fail for some other reasons, I am not exactly sure what the problem is. But as far as issue #144 is concerned, this pull requests solves it @jowens.
```
Start  6: TEST_DOBFS
6/13 Test  #6: TEST_DOBFS .......................***Exception: SegFault  0.07 sec
Start  7: TEST_TOPK
7/13 Test  #7: TEST_TOPK ........................***Failed  Required regular expression not found.Regex=[CORRECT
]  0.00 sec
```
Full output:
```
muhammad@blizzard:~/gunrock/build$ ctest
Test project /home/muhammad/gunrock/build
Start  1: TEST_BFS
1/13 Test  #1: TEST_BFS .........................   Passed    0.17 sec
Start  2: TEST_BC
2/13 Test  #2: TEST_BC ..........................   Passed    1.25 sec
Start  3: TEST_CC
3/13 Test  #3: TEST_CC .......................... …
```
=> Changed executable names for the ctest and make test.

dataset/test-scripts/topc/README.md, dataset/test-scripts/topc/bc-test.sh, dataset/test-scripts/topc/bfs-test.sh, dataset/test-scripts/topc/cc-test.sh, dataset/test-scripts/topc/pr-test.sh, dataset/test-scripts/topc/sssp-test.sh, dataset/test-scripts/topc/topc-test.sh
The variables EXEDIR and DATADIR can now directly be passed from commandline.
Also added a small README.md to document this process of benchmarking on topc datasets.
=> Minor updates to all the scripts in order to pass EXEDIR and DATADIR

gunrock/graphio/market.cuh, gunrock/graphio/utils.cuh
Use of gdb indicated that invalid graphs generated a negative number of nodes, which caused a segmentation fault. This check will display an error message if this is the case and terminate the program. 
This can be tested with the simple graph:
2 2 2
1 1
2 2
which used to seg fault but now will cause an exit out of the program.
=> Added check for invalid graph (exits if number of nodes is negative).

gunrock/graphio/market.cuh
According to MTX format guidelines, the first line of the file cannot be empty. Checks for empty first line, displays error message and exits out if it is empty. Can be tested by adding an empty line above any simple graph, for example:
4 4 8
2 1
3 1
4 1
3 2
4 2
1 3
1 4
3 4
will generate an error and exit out of the program.
=> Check for empty first line in input file stream.

.gitignore, CMakeLists.txt, cmake/FindOpenMP.cmake, cmake/SetSubProject.cmake, gunrock/CMakeLists.txt
Fix #314
```
gangl@GangLiao ~/G/g/g/build> cmake -DGUNROCK_GENCODE_SM30=ON -DGUNROCK_GENCODE_SM50=ON ..
-- The C compiler identification is AppleClang 8.0.0.8000038
-- The CXX compiler identification is AppleClang 8.0.0.8000038
-- Check for working C compiler: /Applications/Xcode8.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode8.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode8.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: …
```
=> Support OpenMP auto build on Mac OS X with GPU

gunrock/app/pr/pr_enactor.cuh, gunrock/oprtr/advance_base.cuh, gunrock/oprtr/all_edges_advance/kernel.cuh, gunrock/oprtr/bypass_filter/kernel.cuh, gunrock/oprtr/edge_map_partitioned_backward/kernel.cuh, gunrock/oprtr/edge_map_partitioned_cull/kernel.cuh, gunrock/oprtr/filter/kernel.cuh, gunrock/util/scan/block_scan.cuh, gunrock/util/types.cuh, tests/BaseMakefile.mk
Adding two _all(1) to sync threads within a warp keeps WarpScan running
=> Workaround for the Volta + CUDA 9.1 bug

CMakeLists.txt
Using this blog post, covered most nvidia cards for the respective SM architectures: http://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
=> Matching SM arch and gencode for nvidia cards.

docker/ubuntu16.04-cuda9.0/dockerfile, docker/ubuntu16.04-cuda9.1/dockerfile
Note: this is minimum working Dockerfile (no metis, always build master branch, ...), we can start from here and further improve it. Following are my in/outs, you can reference when creating documents.
Build:
```
cd docker/ubuntu16.04-cuda9.1/
docker build -t gunrock .
```
Example run:
```
$ nvidia-docker run -ti gunrock
root@b159c6898b1b:/# cd gunrock/build/
root@b159c6898b1b:/gunrock/build# make test
Running tests...
Test project /gunrock/build
Start  1: TEST_BFS
1/11 Test  #1: TEST_BFS .........................   Passed   19.09 sec
Start  2: TEST_BC
2/11 Test  #2: TEST_BC ..........................   Passed    3.40 sec
Start  3: TEST_CC
3/11 Test  #3: TEST_CC ..........................   Passed    1.11 sec
Start  4: TEST_SSSP
4/11 Test  #4: TEST_SSSP ........................   Passed …
```
=> Add initial dockerfiles

gunrock/graphio/graphio.cuh, gunrock/graphio/market.cuh, gunrock/graphio/rgg.cuh, gunrock/graphio/rmat.cuh, gunrock/graphio/small_world.cuh
Adding `--random-edge-values` flag to change the default behavior when edge weights are not specified in the input file.  Previously, Gunrock generated random edge weights by default, which was surprising behavior.  This PR changes the default behavior s.t. edge weights are set to 1 by default.  The old behavior can be exposed via the `--random-edge-values`  flag.
=> `--random-edge-values` flag

gunrock/app/vn/vn_app.cu, gunrock/app/vn/vn_enactor.cuh, gunrock/app/vn/vn_problem.cuh, gunrock/app/vn/vn_test.cuh, tests/vn/Makefile, tests/vn/make_summary.cpp, tests/vn/make_summary.sh, tests/vn/run.sh, tests/vn/run_real.sh, tests/vn/run_rmat.sh, tests/vn/test_vn.cu
For each node in the graph, compute the minimum distance to a node in the source set.  This is equivalent to SSSP, but w/ multiple nodes in the initial frontier.
Running this app w/ `--src a,b,c` uses nodes `a`, `b` and `c` as the source set.  This is slightly different from SSSP, which runs SSSP from `a`, then from `b`, then from `c`.  If we can figure out a way to pass _sets_ of nodes via `src`, I can make the appropriate changes -- this could possibly look like 
```
--src a+b+c,d+e+f
```
to pass sets `{a,b,c}` and `{d,e,f}`.
To see the difference between `vn` and `sssp`, you can look at this diff: 
https://github.com/bkj/gunrock/commit/0e4e94969b012f7dd6191856490b4064cffb17d9
The differences are not particularly large, but since `sssp` is a canonical graph operation, I chose to …
=> [dev-refactor] HIVE VN application

gunrock/app/proj/proj_app.cu, gunrock/app/proj/proj_enactor.cuh, gunrock/app/proj/proj_problem.cuh, gunrock/app/proj/proj_test.cuh, tests/proj/Makefile, tests/proj/test.sh, tests/proj/test_proj.cu
Given a directed graph `G`, `GraphProjections` outputs a graph `Gp` s.t. there is an edge `(u,v)` in `Gp` iff there are edges `(t,u)` and `(t,v)` in `G`.
- (C++) https://gitlab.hiveprogram.com/jfiroz/graph_projection
- (pygunrock) https://github.com/bkj/pygunrock/blob/master/apps/graph_projections.py
- It's a little unclear what the intended use case/topology for this is.  The HIVE slides suggest it's a bipartite graph w/ node sets `U` and `V` s.t. `|V| >> |U|`.  However, the reference implementation is designed to work for arbitrary graphs.  The C++ version above has a flag for bipartite vs. unipartite graphs, but I'm not sure it behaves as desired (I have a question out to the author).
- Often these projected graphs get _very_ dense.  With large graphs, there's a risk that we run out of …
=> [dev-refactor][HIVE] graph_projections

CMakeLists.txt
Also tested #379 in `dev` branch, really sweet speed-ups with using `ninja` instead of `make`. Auto generation of `ninja.builds` using `cmake .. -G Ninja -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja`. 🎉
=> [bug-fix] gtest and gmock working again with dev branch.

CMakeLists.txt, examples/sm/test_sm.cu
@neoblizz 
The ` -std=c++11` parameter was being passed to nvcc multiple times and gunrock would not build.
`test_sm.cu` was passing an `unsigned long long` to the abs function. This is ambiguous because abs expects a signed value.
=> Fix build on Ubuntu 18.04.1 LTS

gunrock/app/mf/mf_app.cu, gunrock/app/mf/mf_enactor.cuh, gunrock/app/mf/mf_helpers.cuh, gunrock/app/mf/mf_problem.cuh, gunrock/app/mf/mf_test.cuh, tests/mf/test_mf.cu
- for Boost cpu reference algorithm I changed for Boykov Kolmogorov instead of Edmonds Karp (so now we have our own "parametric maxflow" as the Boost CPU Reference algorithm)
- Refactoring: I added std::map for mapping pair of vertices to the edge because 2dim array, which I was using instead before, saturated memory and was killing by system (for the biggest test it took around 257GB). It also speeds up a little bit preparing data so waiting for testing is shorter.
=> Update the max flow algorithm

gunrock/graphio/rgg.cuh
#481 
* Fix last entry in `row_offsets`.
* Handle boundary scenarios for first two rows/columns of the grid.
=> RGG: updating row_offsets last value and fix grid boundary bug

gunrock/app/hits/hits_enactor.cuh, gunrock/app/hits/hits_problem.cuh
Performance improvements can be gained by normalizing HITS hub and authority scores every N iterations. By default N = 1 (every iteration), so that the algorithm will function correctly on any graph input. Increasing N presents a risk that the hub and authority scores will overflow (displayed as "nan"), even when using 64-bit values, therefore the user should expect to go through some trial and error for a given graph when attempting to increase N.
=> HITS Optimization

gunrock/graph/csr.cuh, gunrock/graphio/graphio.cuh, tests/tc/tc_main.cu
Added a function to sort CSR edges per vertex. This is required for current TC implementation. Let me know if something else needs to be added or changed.
=> [CSR] adding a sort function

gunrock/util/sysinfo.h
Fix for #348 
Correctly propagates the device number to sysinfo.h so it is written to the json output file.
=> Correctly propogate the device number to sysinfo.h

CMakeLists.txt, cmake/AutoDetectCudaArch.cmake
Gunrock currently compiles for practically all possible compute
capabilites, which requires extremely long build times. It also causes
several warnings to be generated when these various combos of options
go the compiler. This change greatly reduces the amount of code we
normally compile in development, and reduces the complexity of build
configurations.
The file AutoDetectCudaArch.cmake was written by Ahmed Mahmoud.
=> Compile for detected compute capabilities

gunrock/app/pr/pr_test.cuh, gunrock/util/test_utils.cu, gunrock/util/test_utils.h, unittests/test_pointer_location.h, unittests/test_unittests.cu
The fix is in `pr_test.cuh` (was missing `util::DEVICE` in `new_coo` allocation).
Runs like: `./pr --graph-scale 20 --graph-type rmat --graph-edgefactor 32` (from duplicate issue #629) complete as expected.
The additional commits add a utility (and associated gtest) that helped me generate some stack traces during debugging.
=> Fix for pagerank illegal memory access

.gitmodules, cmake/FindModernGPU.cmake, cmake/SetSubProject.cmake, examples/BaseMakefile.mk, gunrock/CMakeLists.txt, gunrock/app/enactor_loop.cuh, gunrock/app/enactor_types.cuh, gunrock/oprtr/LB_CULL_advance/kernel.cuh, gunrock/oprtr/LB_advance/kernel.cuh, gunrock/oprtr/advance/advance_base.cuh, gunrock/oprtr/intersection/kernel.cuh, gunrock/oprtr/oprtr_parameters.cuh, gunrock/util/scan_device.cuh, gunrock/util/sorted_search.cuh
Preparing for the refactor, for which I use moderngpu 2 instead of 1. Hoping to get some a nice performance improvements with the following changes and the fixes issued in PR #673.
=> Upgrading Gunrock's dependency to moderngpu 2.0

CMakeLists.txt
Related to #689 
Please note that this only mimics what is currently done with gcc (disable warning when ENABLE WARNINGS is off). I did not check all warnings shown by nvcc when building. Some seemed fine (converting -1 to unsigned), some can be an issue (using a printf %d to print a templatized variable)
=> opt in warnings nvcc

gunrock/util/info_rapidjson.cuh
@crozhon  I still haven't figured out where the second ```setVal()``` for **load-time** is being called, but commenting out this one works!
=> Prevent duplication of key "load-time" in output json

gunrock/app/enactor_types.cuh, gunrock/oprtr/oprtr_parameters.cuh, gunrock/util/scan_device.cuh, gunrock/util/sorted_search.cuh
After updating moderngpu from 1.0 -> 2.0 we forgot to make sure that the
mgpu calls were on the same stream as our other kernels. Operators using
mgpu's SortedSearch and Scan functions expected them to be complete
before the next kernel call, but since the mgpu context was on the
default stream it executed in parallel with the other kernels. This
caused the output_offsets array used in the following kernel to be incorrect,
and out of bounds memory accesses would occur.
This fix ensures that the mgpu::standard_context_t is setup to use the
same stream as the other kernels. To do so, we keep a context pointer,
allocate it on the heap when the operator parameters are intialized, and
free it when they are released.
=> Fix mgpu memory issues from seperate stream

gunrock/app/test_base.cuh, gunrock/graph/coo.cuh, gunrock/util/test_utils.cu, gunrock/util/test_utils.h
By default all newly created threads are associated with the default
device (see reference). This means newly spawned threads must switch
their device if they are not supposed to use the default device.
When RemoveEdges did not set the device as it should, the graph was
allocated to the wrong GPU. Then subsequent kernels would not find it on
the device they ran on.
In the future I recommend attaching some information about the allocated
device to the underlying Array1D. Without this information, it's
impossible to tell whether a given device pointer is invalid or valid on
a different GPU.
=> SetDevice after spawning OpenMP threads

gunrock/app/problem_base.cuh
I added single graph release to the problem_base.cuh code a bit back.
But that was a mistake. When num_gpus == 1, we use SetPointer to create
our sub_graphs array, rather than allocating individual components. So
when num_gpus == 1, no Release should be happening in the problem. This
caused the graph to be invalid during subsequent runs when multiple
parameters were set.
=> Fix Release issue for multiple parameter switches

gunrock/app/sm/sm_app.cu, gunrock/app/sm/sm_app.cuh, gunrock/app/sm/sm_problem.cuh, gunrock/gunrock.h, unittests/test_lib_sm.h
Leyuan extended Gunrock's SM application to return mappings between query graph and the base graph. However the pointer to the allocated memory that contained the mappings was not passed to the C API properly.
This pull request fixes the issue. I included a small test case in `test_lib_sm.h`.
=> Fix SM mappings bug

examples/dynamic_graph/test_dynamic_graph.cu, gunrock/graph/dynamic_graph/dynamic_graph_unweighted.cuh, gunrock/graph/dynamic_graph/dynamic_graph_weighted.cuh, gunrock/graph/dynamic_graph/slabhash_graph_base.cuh, unittests/test_dynamic_graph.h, unittests/test_graph_iterator.h
- Moved the hash table base slabs allocation to the allocate function (where we know how many base slabs we need)
- Added an option for batched edge insertion functions to avoid doubling edges when the batch is already undirected
=> Fix graph memory allocation and undirected insertion batches

examples/rw/Makefile, examples/rw/test_rw.cu, gunrock/app/rw/rw_app.cu, gunrock/app/rw/rw_enactor.cuh, gunrock/app/rw/rw_problem.cuh, gunrock/oprtr/1D_oprtr/for_all.cuh
Swap out single gpu for_all operations with multi-gpu equivalents. While the various walk modes run to completion, the results are incorrect (lots of -1s in the output) and further debugging is necessary.
=> Bring in rw (random walk) multi-gpu work in progress

examples/louvain/Makefile, gunrock/app/louvain/louvain_enactor.cuh, gunrock/util/context.hpp, gunrock/util/reduce_device.cuh, gunrock/util/select_device.cuh, gunrock/util/sort_device.cuh
@crozhon had the right idea of adding a `ArrayType` template parameter to the templated functions with `util::Array1D` arguments. I extended that to all the other commented out calls that were having this issue.
The other problem I ran into was a linking issue with the [ceil_divide](https://github.com/gunrock/gunrock/compare/multigpu...cameronshinn:cameron-multigpu?expand=1#diff-4969aa931d4336e0aba64479d2dc37fb8abab5af5d2262672d45aa99804431bbL230-L231) function. It was being included in multiple places which made ld unsure of which one to use (despite them all being the same). Making the function `inline` fixes the problem.
https://stackoverflow.com/a/34618587
Note that these changes now make it that so louvain *builds*, but has not been run. I was getting errors trying to build in …
=> Fix louvain to build with multi-GPU

gunrock/app/bc/bc_test.cuh
Call is 
```
DisplaySolution(h_sigmas, h_bc_values, num_vertices, quiet);
```
not
```
DisplaySolution(h_bc_values, h_sigmas, num_vertices, quiet);
```
=> [BUG] typo in bc_test.cuh

gunrock/util/reduce_device.cuh, gunrock/util/select_device.cuh, gunrock/util/sort_device.cuh
Internal CUB APIs in sort, select, and reduce are changed to external ones.
Fixes #857.
=> Use external CUB API instead of internal ones

gunrock/util/scan/cooperative_scan.cuh, gunrock/util/scan/warp_scan.cuh
`__syncthreads` was used to fix the hazards, but it might be unnecessary
to go that far.
Do you know more about these scan functions @neoblizz? Does CUB have this same function? Should we just use that?
=> Fix RAW and WAR hazards found using cuda-memcheck

include/gunrock/algorithms/bc.hxx
This bug makes bc essentially not run unless performance analysis is turned on.
I found it while testing my graph builder updates.
=> fix bc bug (introduced with perf analysis)

benchmarks/spgemm_bench.cu, examples/algorithms/spgemm/spgemm.cu, include/gunrock/algorithms/spgemm.hxx, include/gunrock/framework/frontier/vector_frontier.hxx, include/gunrock/framework/operators/configs.hxx
This PR adds the lambda function for SpGEMM. 
All checks passed except documentation. Not sure why...
Some updates that can be done for the future:
- Using advance instead of parallel-for
- When graph view_t can do both CSR and CSC in the same view, the inputs for B can be updated. Currently, the 2 separate views are passed to spgemm::run() as parameters
=> lambda function for SpGEMM

include/gunrock/algorithms/mst.hxx
The switch to par_nosync introduced a bug in MST where it would exit early. An exit condition was checked asynchronously before the value was updated. This fixes that issue.
=> Fix MST bug introduced with par_nosync
